version: '3'
services:
    postgres:
        container_name: ${DOCKER_POSTGRES_CONTAINER_NAME:-myth-caster-postgres}
        image: postgres:${DOCKER_POSTGRES_TAG:-12}
        env_file:
            - ./mythcaster.env
        volumes:
            - ${DOCKER_POSTGRES_DATA_DIR:-/data/postgres/myth-caster-api}:/var/lib/postgresql/data
        networks:
            - container-bridge
    django:
        container_name: ${DOCKER_DJANGO_CONTAINER_NAME:-myth-caster-django}
        build: .
        env_file:
            - ./mythcaster.env
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "${DOCKER_DJANGO_PORT:-8000}:${DOCKER_DJANGO_PORT:-8000}"
        depends_on:
            - postgres
        networks:
            - container-bridge
networks:
    container-bridge:
        driver: bridge
