# Generated by Django 3.1.1 on 2020-09-21 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('character', '0006_auto_20200920_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('save_or_roll', models.CharField(choices=[('S', 'Saving Throw'), ('R', 'Roll a Spell Attack'), ('N', 'None/Other')], db_index=True, default='N', max_length=1)),
                ('damage', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('authorized_editors', models.ManyToManyField(blank=True, related_name='_spell_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('classes', models.ManyToManyField(to='character.CharacterClass')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
