# Generated by Django 3.1.1 on 2020-09-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='damage_dice',
            new_name='damage',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='damage_type',
        ),
    ]
