# Generated by Django 3.1.1 on 2020-09-20 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventuringgear',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_adventuringgear_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='armor',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_armor_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tool',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_tool_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_weapon_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wondrousitem',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_wondrousitem_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
