# Generated by Django 3.0.10 on 2020-09-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_mastering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(db_index=True, default='file', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
