# Generated by Django 3.0.10 on 2020-09-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_mastering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemasterfile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
