# Generated by Django 3.1.1 on 2020-09-13 23:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ancestry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('features', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinLengthValidator(1)])),
                ('strength', models.PositiveIntegerField(default=10)),
                ('dexterity', models.PositiveIntegerField(default=10)),
                ('constitution', models.PositiveIntegerField(default=10)),
                ('intelligence', models.PositiveIntegerField(default=10)),
                ('wisdom', models.PositiveIntegerField(default=10)),
                ('charisma', models.PositiveIntegerField(default=10)),
                ('proficient_light_armor', models.BooleanField(default=False)),
                ('proficient_medium_armor', models.BooleanField(default=False)),
                ('proficient_heavy_armor', models.BooleanField(default=False)),
                ('proficient_shields', models.BooleanField(default=False)),
                ('proficient_simple', models.BooleanField(default=False)),
                ('proficient_martial', models.BooleanField(default=False)),
                ('proficient_tools', models.TextField(default='')),
                ('proficient_languages', models.TextField(default='')),
                ('proficient_other', models.TextField(default='')),
                ('ancestry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.ancestry')),
                ('authorized_editors', models.ManyToManyField(related_name='_character_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('inventory_adventuring_gear', models.ManyToManyField(to='equipment.AdventuringGear')),
                ('inventory_armors', models.ManyToManyField(to='equipment.Armor')),
                ('inventory_tools', models.ManyToManyField(to='equipment.Tool')),
                ('inventory_weapons', models.ManyToManyField(to='equipment.Weapon')),
                ('inventory_wondrous_items', models.ManyToManyField(to='equipment.WondrousItem')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proficient_skills', models.ManyToManyField(to='skills.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
