# Generated by Django 3.1.1 on 2020-09-20 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancestry',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_ancestry_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='background',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_background_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_character_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_characterclass_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classandlevel',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_classandlevel_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feature',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_feature_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='featuresatlevel',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_featuresatlevel_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryadventuringgear',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_inventoryadventuringgear_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryarmor',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_inventoryarmor_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorytool',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_inventorytool_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryweapon',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_inventoryweapon_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorywondrousitem',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_inventorywondrousitem_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skillproficiency',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_skillproficiency_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spellslotsatlevel',
            name='authorized_editors',
            field=models.ManyToManyField(blank=True, related_name='_spellslotsatlevel_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
