# Generated by Django 3.1.1 on 2020-09-14 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
        ('skills', '0002_auto_20200913_2359'),
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('features', models.TextField()),
                ('authorized_editors', models.ManyToManyField(related_name='_background_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('granted_armors', models.ManyToManyField(to='equipment.Armor')),
                ('granted_skills_default', models.ManyToManyField(to='skills.Skill')),
                ('granted_tools', models.ManyToManyField(to='equipment.Tool')),
                ('granted_weapons', models.ManyToManyField(to='equipment.Weapon')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
