# Generated by Django 3.1.1 on 2020-09-15 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200915_0039'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0002_auto_20200913_2359'),
        ('character', '0002_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('hit_die', models.CharField(choices=[('4', 'd4'), ('6', 'd6'), ('8', 'd8'), ('10', 'd10'), ('12', 'd12'), ('20', 'd20')], max_length=2)),
                ('description', models.TextField()),
                ('skill_number', models.PositiveIntegerField(default=0)),
                ('multiclass_skill_number', models.PositiveIntegerField(default=0)),
                ('equipment_choices', models.TextField()),
                ('major_saving_throw', models.CharField(choices=[('DEX', 'dexterity'), ('CON', 'constitution'), ('WIS', 'wisdom')], max_length=3)),
                ('minor_saving_throw', models.CharField(choices=[('STR', 'strength'), ('INT', 'intelligence'), ('CHA', 'charisma')], max_length=3)),
                ('proficient_light_armor', models.BooleanField(default=False)),
                ('proficient_heavy_armor', models.BooleanField(default=False)),
                ('proficient_shields', models.BooleanField(default=False)),
                ('proficient_martial_weapons', models.BooleanField(default=False)),
                ('proficient_simple_weapons', models.BooleanField(default=False)),
                ('proficient_other', models.TextField(blank=True, null=True)),
                ('authorized_editors', models.ManyToManyField(related_name='_characterclass_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('prerequisite_strength', models.IntegerField(db_index=True, default=0)),
                ('prerequisite_dexterity', models.IntegerField(db_index=True, default=0)),
                ('prerequisite_constitution', models.IntegerField(db_index=True, default=0)),
                ('prerequisite_intelligence', models.IntegerField(db_index=True, default=0)),
                ('prerequisite_wisdom', models.IntegerField(db_index=True, default=0)),
                ('prerequisite_charisma', models.IntegerField(db_index=True, default=0)),
                ('authorized_editors', models.ManyToManyField(related_name='_feature_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellSlotsAtLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_level', models.PositiveIntegerField(db_index=True)),
                ('level_1', models.PositiveIntegerField(default=0)),
                ('level_2', models.PositiveIntegerField(default=0)),
                ('level_3', models.PositiveIntegerField(default=0)),
                ('level_4', models.PositiveIntegerField(default=0)),
                ('level_5', models.PositiveIntegerField(default=0)),
                ('level_6', models.PositiveIntegerField(default=0)),
                ('level_7', models.PositiveIntegerField(default=0)),
                ('level_8', models.PositiveIntegerField(default=0)),
                ('level_9', models.PositiveIntegerField(default=0)),
                ('authorized_editors', models.ManyToManyField(related_name='_spellslotsatlevel_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='background',
            old_name='granted_skills_default',
            new_name='granted_skills',
        ),
        migrations.RemoveField(
            model_name='character',
            name='level',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficient_skills',
        ),
        migrations.AddField(
            model_name='ancestry',
            name='authorized_editors',
            field=models.ManyToManyField(related_name='_ancestry_authorized_editors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ancestry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='background',
            name='granted_languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='background',
            name='starting_equipment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='background',
            name='starting_gold',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='character.background'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='hit_point_current',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='hit_point_total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='initiative_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='jack_of_all_trades',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='temporary_hit_point_total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ancestry',
            name='features',
        ),
        migrations.AlterField(
            model_name='ancestry',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='background',
            name='features',
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='proficient_languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='proficient_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='proficient_tools',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SpellsKnownAtLevel',
            fields=[
                ('spellslotsatlevel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.spellslotsatlevel')),
                ('level_0', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('character.spellslotsatlevel',),
        ),
        migrations.CreateModel(
            name='SubAncestry',
            fields=[
                ('ancestry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.ancestry')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='character.ancestry')),
            ],
            options={
                'abstract': False,
            },
            bases=('character.ancestry',),
        ),
        migrations.CreateModel(
            name='SkillProficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('P', 'Proficient'), ('E', 'Expert')], default='P', max_length=1)),
                ('authorized_editors', models.ManyToManyField(related_name='_skillproficiency_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skills.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryWondrousItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('authorized_editors', models.ManyToManyField(related_name='_inventorywondrousitem_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.wondrousitem')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('authorized_editors', models.ManyToManyField(related_name='_inventoryweapon_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.weapon')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('authorized_editors', models.ManyToManyField(related_name='_inventorytool_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.tool')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryArmor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('authorized_editors', models.ManyToManyField(related_name='_inventoryarmor_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.armor')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryAdventuringGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('authorized_editors', models.ManyToManyField(related_name='_inventoryadventuringgear_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.adventuringgear')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturesAtLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_level', models.PositiveIntegerField(db_index=True)),
                ('authorized_editors', models.ManyToManyField(related_name='_featuresatlevel_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('features', models.ManyToManyField(to='character.Feature')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassAndLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('authorized_editors', models.ManyToManyField(related_name='_classandlevel_authorized_editors_+', to=settings.AUTH_USER_MODEL)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.characterclass')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='characterclass',
            name='features',
            field=models.ManyToManyField(to='character.FeaturesAtLevel'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='skill_choices',
            field=models.ManyToManyField(to='skills.Skill'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='spell_slots',
            field=models.ManyToManyField(related_name='character_class_spell_slots', to='character.SpellSlotsAtLevel'),
        ),
        migrations.AddField(
            model_name='character',
            name='class_levels',
            field=models.ManyToManyField(to='character.ClassAndLevel'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(to='character.SkillProficiency'),
        ),
        migrations.AddField(
            model_name='ancestry',
            name='features',
            field=models.ManyToManyField(to='character.Feature'),
        ),
        migrations.AddField(
            model_name='background',
            name='features',
            field=models.ManyToManyField(to='character.Feature'),
        ),
        migrations.AlterField(
            model_name='character',
            name='inventory_adventuring_gear',
            field=models.ManyToManyField(to='character.InventoryAdventuringGear'),
        ),
        migrations.AlterField(
            model_name='character',
            name='inventory_armors',
            field=models.ManyToManyField(to='character.InventoryArmor'),
        ),
        migrations.AlterField(
            model_name='character',
            name='inventory_tools',
            field=models.ManyToManyField(to='character.InventoryTool'),
        ),
        migrations.AlterField(
            model_name='character',
            name='inventory_weapons',
            field=models.ManyToManyField(to='character.InventoryWeapon'),
        ),
        migrations.AlterField(
            model_name='character',
            name='inventory_wondrous_items',
            field=models.ManyToManyField(to='character.InventoryWondrousItem'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='spells_known',
            field=models.ManyToManyField(related_name='character_class_spells_known', to='character.SpellsKnownAtLevel'),
        ),
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('characterclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.characterclass')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='character.characterclass')),
            ],
            options={
                'abstract': False,
            },
            bases=('character.characterclass',),
        ),
    ]
