# Generated by Django 3.1.1 on 2020-09-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20200920_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='initiative_bonus',
            new_name='misc_initiative_bonus',
        ),
    ]
