# Generated by Django 3.1.1 on 2020-09-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200920_2245'),
        ('skills', '0002_auto_20200920_2245'),
        ('character', '0004_auto_20200920_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='suggested_bonds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='background',
            name='suggested_flaws',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='background',
            name='suggested_ideals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='background',
            name='suggested_personality_traits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='granted_armors',
            field=models.ManyToManyField(blank=True, to='equipment.Armor'),
        ),
        migrations.AlterField(
            model_name='background',
            name='granted_skills',
            field=models.ManyToManyField(blank=True, to='skills.Skill'),
        ),
        migrations.AlterField(
            model_name='background',
            name='granted_tools',
            field=models.ManyToManyField(blank=True, to='equipment.Tool'),
        ),
        migrations.AlterField(
            model_name='background',
            name='granted_weapons',
            field=models.ManyToManyField(blank=True, to='equipment.Weapon'),
        ),
    ]
