# Generated by Django 3.1.1 on 2020-09-20 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20200920_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subancestry',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='character.ancestry'),
        ),
    ]
