# Generated by Django 3.1.1 on 2020-09-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20200920_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='background',
            old_name='granted_armors',
            new_name='suggested_armors',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='granted_languages',
            new_name='suggested_languages',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='granted_skills',
            new_name='suggested_skills',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='granted_tools',
            new_name='suggested_tools',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='granted_weapons',
            new_name='suggested_weapons',
        ),
    ]
