# Generated by Django 3.1.1 on 2020-09-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0001_initial'),
        ('character', '0007_auto_20200922_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='condition',
            field=models.ManyToManyField(blank=True, related_name='characters_with_condition', to='condition.Condition'),
        ),
    ]
