# Generated by Django 3.1.1 on 2020-09-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_character_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
