# Generated by Django 3.1.1 on 2020-09-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_character_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='condition',
            new_name='conditions',
        ),
    ]
