# Generated by Django 3.1.1 on 2020-09-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20200920_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='ability',
            field=models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma')], default='STR', max_length=3),
            preserve_default=False,
        ),
    ]
